freelife: field.c File Reference
field.c File Reference
Macros
#define MAX_POINTS 100
Functions
static gboolean on_fielddraw_button_press_event (GtkWidget *widget, GdkEventButton *event, gpointer user_data)
static gboolean on_fielddraw_button_release_event (GtkWidget *widget, GdkEventButton *event, gpointer user_data)
static gboolean on_fielddraw_motion_notify_event (GtkWidget *widget, GdkEventMotion *event, gpointer user_data)
static gboolean on_fielddraw_key_press_event (GtkWidget *widget, GdkEventKey *event, gpointer user_data)
static gboolean on_fielddraw_configure_event (GtkWidget *widget, GdkEventConfigure *event, gpointer user_data)
static gboolean on_field_configure_event (GtkWidget *widget, GdkEventConfigure *event, gpointer user_data)
static void on_stop_clicked (GtkButton *button, gpointer user_data)
static void create_hand_field (void)
void redraw_pixmap_field (void)
static gboolean on_fielddraw_expose_event (GtkWidget *widget, GdkEventExpose *event, gpointer user_data)
void create_field (void)
Macro Definition Documentation
#define MAX_POINTS 100
Referenced by create_hand_field().
Function Documentation
static gboolean on_fielddraw_button_press_event (GtkWidget * widget, GdkEventButton * event, gpointer user_data) static
Definition at line 22 of file field.c.
References config, fielddraw, CONFIG::life_height, CONFIG::life_width, zoom_xoffset, and zoom_yoffset.
Referenced by create_field().
static gboolean on_fielddraw_button_release_event (GtkWidget * widget, GdkEventButton * event, gpointer user_data) static
Definition at line 81 of file field.c.
References fielddraw.
Referenced by create_field().
static gboolean on_fielddraw_motion_notify_event (GtkWidget * widget, GdkEventMotion * event, gpointer user_data) static
Definition at line 97 of file field.c.
References config, CONFIG::life_height, CONFIG::life_width, zoom_xoffset, and zoom_yoffset.
Referenced by create_field().
static gboolean on_fielddraw_key_press_event (GtkWidget * widget, GdkEventKey * event, gpointer user_data) static
Definition at line 132 of file field.c.
Referenced by create_field().
static gboolean on_fielddraw_configure_event (GtkWidget * widget, GdkEventConfigure * event, gpointer user_data) static
Definition at line 147 of file field.c.
Referenced by create_field().
static gboolean on_field_configure_event (GtkWidget * widget, GdkEventConfigure * event, gpointer user_data) static
Definition at line 159 of file field.c.
Referenced by create_field().
static void on_stop_clicked (GtkButton * button, gpointer user_data) static
Definition at line 171 of file field.c.
References end_comp_generations.
Referenced by create_field().
static void create_hand_field (void) static
Definition at line 179 of file field.c.
References CURRENT_FIELD, field_off_color, field_on_color, get_zoom_infos(), life_bpl, mask, MAX_POINTS, on_npoints, and on_points.
Referenced by redraw_pixmap_field().
void redraw_pixmap_field (void)
Definition at line 261 of file field.c.
References config, create_hand_field(), fielddraw, CONFIG::life_height, and CONFIG::life_width.
Referenced by on_fielddraw_expose_event(), restore_gen0(), and restore_prev_gen().
static gboolean on_fielddraw_expose_event (GtkWidget * widget, GdkEventExpose * event, gpointer user_data) static
Definition at line 271 of file field.c.
References redraw_pixmap_field().
Referenced by create_field().
void create_field (void)
Definition at line 284 of file field.c.
References btn_stop, close_app(), config, create_color(), field_off_color, field_on_color, field_scrolledwnd, fielddraw, hsep_stable, info_birth, info_death, info_gen, info_pop, label_stable, CONFIG::life_height, CONFIG::life_width, on_field_configure_event(), on_fielddraw_button_press_event(), on_fielddraw_button_release_event(), on_fielddraw_configure_event(), on_fielddraw_expose_event(), on_fielddraw_key_press_event(), on_fielddraw_motion_notify_event(), and on_stop_clicked().
Referenced by main().