freelife: life.c File Reference
life.c File Reference
Macros
#define MAX_POINTS 1000
#define COUNT(val, nb, pw, mask, icol)
#define SHOW(w, v)
Functions
static void test_gen_stable (const UBYTE *curr_gen)
static void test_pop_stable (void)
UBYTE * field_to_use (void)
void compute_gen (void)
void show_life_pop (void)
void show_infos (void)
void compute_generations (void)
void restore_prev_gen (void)
void restore_gen0 (void)
Variables
static gint on_npoints
static gint off_npoints
static GdkPoint on_points [MAX_POINTS]
static GdkPoint off_points [MAX_POINTS]
Macro Definition Documentation
#define MAX_POINTS 1000
Definition at line 21 of file life.c.
#define COUNT (val, nb, pw, mask, icol)
Definition at line 108 of file life.c.
Referenced by compute_gen().
#define SHOW (w, v)
Value:
if (v == -1) \
        strcpy( msg, "" ); \
    else \
        sprintf( msg, "%d", v ); \
    gtk_label_set_text( GTK_LABEL( w ), msg )
Referenced by show_infos().
Function Documentation
static void test_gen_stable (const UBYTE * curr_gen) static
Definition at line 28 of file life.c.
References gen_kept, gen_kept_nb, hsep_stable, is_stability, label_stable, life_birth, life_death, life_size, and stability_period.
Referenced by compute_gen().
static void test_pop_stable (void) static
Definition at line 82 of file life.c.
References gen_kept_nb, gen_kept_popnb, hsep_stable, is_stability, label_stable, max_nb_gen_kept, and stability_period.
UBYTE* field_to_use (void)
Definition at line 150 of file life.c.
References life_gen.
Referenced by compute_gen().
void compute_gen (void)
Definition at line 157 of file life.c.
References config, COUNT, field_off_color, field_on_color, field_to_use(), fielddraw, gen0_kept, gen_kept, gen_kept_base, gen_kept_nb, gen_kept_popnb, life_birth, life_bpl, life_death, life_gen, CONFIG::life_height, life_pop, life_size, life_stable, CONFIG::life_width, max_nb_gen_kept, off_npoints, off_points, on_npoints, on_points, show_infos(), test_gen_stable(), and zoom_area.
Referenced by compute_generations(), and on_LifeNextGen_activate().
void show_life_pop (void)
Definition at line 318 of file life.c.
References info_pop, and life_pop.
Referenced by on_zoom_area_button_press_event(), on_zoom_area_motion_notify_event(), and show_infos().
void show_infos (void)
Definition at line 332 of file life.c.
References info_birth, info_death, info_gen, life_birth, life_death, life_gen, SHOW, and show_life_pop().
Referenced by clear_life(), compute_gen(), main(), restore_gen0(), and restore_prev_gen().
void compute_generations (void)
Definition at line 357 of file life.c.
References btn_stop, compute_gen(), end_comp_generations, is_comp_generations, is_stability, life_gen, and life_pop.
Referenced by on_FileNextGens_activate(), and on_LifeSeekInterGen_activate().
void restore_prev_gen (void)
Definition at line 520 of file life.c.
References gen_kept, gen_kept_nb, is_comp_generations, is_stability, life_birth, life_death, life_gen, life_pop, life_size, life_stable, redraw_pixmap_field(), redraw_pixmap_zoom(), and show_infos().
Referenced by on_FilePrevGen_activate().
void restore_gen0 (void)
Definition at line 600 of file life.c.
References gen0_kept, gen_kept_nb, life_birth, life_death, life_gen, life_pop, life_size, life_stable, redraw_pixmap_field(), redraw_pixmap_zoom(), and show_infos().
Referenced by on_LifeRestoreStartingGen_activate().
Variable Documentation
gint on_npoints static
Definition at line 22 of file life.c.
Referenced by compute_gen(), and create_hand_field().
gint off_npoints static
Definition at line 22 of file life.c.
Referenced by compute_gen().
GdkPoint on_points[MAX_POINTS] static
Definition at line 24 of file life.c.
Referenced by compute_gen(), and create_hand_field().
GdkPoint off_points[MAX_POINTS] static
Definition at line 24 of file life.c.
Referenced by compute_gen().