freelife: settings.h File Reference
settings.h File Reference
Functions
void default_config (void)
gboolean on_settings_life_height_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
gboolean on_settings_life_width_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
gboolean on_settings_life_lifesavednb_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
void on_settings_ok_clicked (GtkButton *button, gpointer user_data)
void on_settings_cancel_clicked (GtkButton *button, gpointer user_data)
void create_settings (void)
Function Documentation
void default_config (void)
Definition at line 28 of file settings.c.
References config, rndgen_t::h, CONFIG::life_height, CONFIG::life_width, CONFIG::lifesavednb, rndgen_t::nbmax, rndgen_t::nbmin, rndgen, rndgen_t::w, rndgen_t::x, and rndgen_t::y.
Referenced by main().
gboolean on_settings_life_height_event (GtkWidget * widget, GdkEvent * event, gpointer user_data)
Definition at line 68 of file settings.c.
References config, CONFIG::life_height, and settings_ok.
Referenced by create_settings().
gboolean on_settings_life_width_event (GtkWidget * widget, GdkEvent * event, gpointer user_data)
Definition at line 84 of file settings.c.
References config, CONFIG::life_width, and settings_ok.
Referenced by create_settings().
gboolean on_settings_life_lifesavednb_event (GtkWidget * widget, GdkEvent * event, gpointer user_data)
Definition at line 100 of file settings.c.
References config, CONFIG::lifesavednb, and settings_ok.
Referenced by create_settings().
void on_settings_ok_clicked (GtkButton * button, gpointer user_data)
Definition at line 116 of file settings.c.
Referenced by create_settings().
void on_settings_cancel_clicked (GtkButton * button, gpointer user_data)
Definition at line 123 of file settings.c.
Referenced by create_settings().
void create_settings (void)
Definition at line 130 of file settings.c.
References on_settings_cancel_clicked(), on_settings_life_height_event(), on_settings_life_lifesavednb_event(), on_settings_life_width_event(), on_settings_ok_clicked(), set_notebook_tab(), settings_life_height, settings_life_lifesavednb, settings_life_width, settings_ok, and write_config_to_dialog().
Referenced by on_OptionsSettings_activate().