freelife: utils.c File Reference
utils.c File Reference
Functions
GdkGC * create_color (GtkWidget *wgt, const long red, const long green, const long blue)
void set_notebook_tab (GtkWidget *notebook, gint page_num, GtkWidget *widget)
double now (void)
Function Documentation
GdkGC* create_color (GtkWidget * wgt, const long red, const long green, const long blue)
Definition at line 23 of file utils.c.
Referenced by create_field(), and create_zoom().
void set_notebook_tab (GtkWidget * notebook, gint page_num, GtkWidget * widget)
Definition at line 60 of file utils.c.
Referenced by create_settings().
double now (void)
Definition at line 81 of file utils.c.
Referenced by redraw_pixmap_zoom().