freelife: zoom.c File Reference
zoom.c File Reference
Functions
gint close_app (GtkWidget *widget, gpointer data)
static void draw_zoom_cell_on (const int x, const int y)
static void draw_zoom_cell_off (const int x, const int y)
void on_FileLoad_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FileSave_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FileSaveText_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FilePrint_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FileExit_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_OptionsGrid_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_OptionsSettings_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeClear_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeCenterZoom_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeCenterGeneration_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FilePrevGen_activate (GtkMenuItem *menuitem, gpointer user_data)
void clear_pending_events (void)
void on_LifeNextGen_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_FileNextGens_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeRestoreStartingGen_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeStats_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeGraph_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeInterGen_7_172_activate (GtkMenuItem *menuitem, gpointer user_data)
static void build_random_population (int clean_maxnb_gen)
void on_LifeRandomGen_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_LifeSeekInterGen_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_RulesStd_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_RuleDefine_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_RuleLoad_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_RuleSave_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_HelpRules_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_HelpAbout_activate (GtkMenuItem *menuitem, gpointer user_data)
static gboolean on_zoom_area_button_press_event (GtkWidget *widget, GdkEventButton *event, gpointer user_data)
static gboolean on_zoom_area_motion_notify_event (GtkWidget *widget, GdkEventMotion *event, gpointer user_data)
void get_zoom_infos (void)
static gboolean on_zoom_area_configure_event (GtkWidget *widget, GdkEventConfigure *event, gpointer user_data)
int redraw_pixmap_zoom (void)
static gboolean on_zoom_area_expose_event (GtkWidget *widget, GdkEventExpose *event, gpointer user_data)
static gboolean on_zoom_scrolledwindow_event (GtkWidget *widget, GdkEvent *event, gpointer user_data)
static void create_menu_btn (GtkWidget *wgt_menubar, GtkWidget **wgt_menubtn, GtkWidget **wgt_menu, char *label, int side, void(*pcb_activate)(GtkMenuItem *, gpointer))
GtkWidget * create_menu_item (GtkWidget *wgt_menu, char *label, char *xpm[], int sensitive, int acc_key, int acc_control, GCallback cb, gpointer user_data)
void create_zoom (void)
void center_zoom (void)
int is_grid (void)
void enable_LifeCenterGeneration (const int flag)
void enable_PrevGen (const int flag)
void enable_NextGen (const int flag)
void enable_NextGens (const int flag)
void enable_RestoreStartingGen (const int flag)
Variables
static GtkWidget * LifeCenterGeneration
static GtkWidget * LifePrevGen
static GtkWidget * LifeNextGen
static GtkWidget * LifeNextGens
static GtkWidget * LifeRestoreStartingGen
Function Documentation
gint close_app (GtkWidget * widget, gpointer data)
Definition at line 28 of file zoom.c.
Referenced by create_field(), and create_zoom().
static void draw_zoom_cell_on (const int x, const int y) static
Definition at line 40 of file zoom.c.
References ZOOM_CELL_HEIGHT, ZOOM_CELL_WIDTH, zoom_on_color, and ZOOM_ON_SZ.
Referenced by redraw_pixmap_zoom().
static void draw_zoom_cell_off (const int x, const int y) static
Definition at line 58 of file zoom.c.
References ZOOM_CELL_HEIGHT, ZOOM_CELL_WIDTH, zoom_off_color, and ZOOM_OFF_SZ.
Referenced by redraw_pixmap_zoom().
void on_FileLoad_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 69 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_FileSave_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 81 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_FileSaveText_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 93 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_FilePrint_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 105 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_FileExit_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 117 of file zoom.c.
Referenced by create_zoom().
void on_OptionsGrid_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 125 of file zoom.c.
References zoom_area.
Referenced by create_zoom().
void on_OptionsSettings_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 133 of file zoom.c.
References create_settings(), and is_comp_generations.
Referenced by create_zoom().
void on_LifeClear_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 146 of file zoom.c.
References clear_life(), and is_comp_generations.
Referenced by create_zoom().
void on_LifeCenterZoom_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 159 of file zoom.c.
References center_zoom().
Referenced by create_zoom().
void on_LifeCenterGeneration_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 166 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_FilePrevGen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 178 of file zoom.c.
References is_comp_generations, and restore_prev_gen().
Referenced by create_zoom().
void clear_pending_events (void)
Definition at line 219 of file zoom.c.
Referenced by on_LifeNextGen_activate().
void on_LifeNextGen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 247 of file zoom.c.
References clear_pending_events(), compute_gen(), is_comp_generations, and life_gen.
Referenced by create_zoom().
void on_FileNextGens_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 268 of file zoom.c.
References compute_generations(), and is_comp_generations.
Referenced by create_zoom().
void on_LifeRestoreStartingGen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 283 of file zoom.c.
References is_comp_generations, and restore_gen0().
Referenced by create_zoom().
void on_LifeStats_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 297 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_LifeGraph_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 310 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_LifeInterGen_7_172_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 323 of file zoom.c.
References clear_life(), fielddraw, is_comp_generations, life_birth, life_bpl, life_death, life_gen, life_pop, and life_stable.
Referenced by create_zoom().
static void build_random_population (int clean_maxnb_gen) static
Definition at line 349 of file zoom.c.
References clear_life(), fielddraw, GENRND, rndgen_t::h, life_birth, life_bpl, life_death, life_gen, life_pop, life_stable, mask, rndgen_t::nbmax, rndgen_t::nbmin, rndgen, rndgen_t::w, rndgen_t::x, and rndgen_t::y.
Referenced by on_LifeRandomGen_activate(), and on_LifeSeekInterGen_activate().
void on_LifeRandomGen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 371 of file zoom.c.
References build_random_population(), and is_comp_generations.
Referenced by create_zoom().
void on_LifeSeekInterGen_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 390 of file zoom.c.
References build_random_population(), compute_generations(), end_comp_generations, gen0_kept, is_comp_generations, life_gen, life_pop, life_size, and zoom_maxgen.
Referenced by create_zoom().
void on_RulesStd_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 433 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_RuleDefine_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 446 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_RuleLoad_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 459 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_RuleSave_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 472 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_HelpRules_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 485 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
void on_HelpAbout_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 498 of file zoom.c.
References is_comp_generations.
Referenced by create_zoom().
static gboolean on_zoom_area_button_press_event (GtkWidget * widget, GdkEventButton * event, gpointer user_data) static
Definition at line 512 of file zoom.c.
References config, CURRENT_FIELD, fielddraw, is_comp_generations, life_bpl, CONFIG::life_height, life_pop, CONFIG::life_width, mask, show_life_pop(), zoom_area, ZOOM_CELL_HEIGHT, and ZOOM_CELL_WIDTH.
Referenced by create_zoom().
static gboolean on_zoom_area_motion_notify_event (GtkWidget * widget, GdkEventMotion * event, gpointer user_data) static
Definition at line 583 of file zoom.c.
References config, CURRENT_FIELD, fielddraw, is_comp_generations, life_bpl, CONFIG::life_height, life_pop, CONFIG::life_width, mask, show_life_pop(), zoom_area, ZOOM_CELL_HEIGHT, ZOOM_CELL_WIDTH, and zoom_xy.
Referenced by create_zoom().
void get_zoom_infos (void)
Definition at line 672 of file zoom.c.
References ZOOM_CELL_HEIGHT, and ZOOM_CELL_WIDTH.
Referenced by center_zoom(), create_hand_field(), on_zoom_area_configure_event(), on_zoom_scrolledwindow_event(), and redraw_pixmap_zoom().
static gboolean on_zoom_area_configure_event (GtkWidget * widget, GdkEventConfigure * event, gpointer user_data) static
Definition at line 689 of file zoom.c.
References get_zoom_infos().
Referenced by create_zoom().
int redraw_pixmap_zoom (void)
Definition at line 709 of file zoom.c.
References CURRENT_FIELD, draw_zoom_cell_off(), draw_zoom_cell_on(), get_zoom_infos(), is_grid(), life_bpl, mask, now(), zoom_area, ZOOM_CELL_HEIGHT, ZOOM_CELL_WIDTH, and zoom_none_color.
Referenced by on_zoom_area_expose_event(), restore_gen0(), and restore_prev_gen().
static gboolean on_zoom_area_expose_event (GtkWidget * widget, GdkEventExpose * event, gpointer user_data) static
Definition at line 782 of file zoom.c.
References redraw_pixmap_zoom().
Referenced by create_zoom().
static gboolean on_zoom_scrolledwindow_event (GtkWidget * widget, GdkEvent * event, gpointer user_data) static
Definition at line 795 of file zoom.c.
References fielddraw, get_zoom_infos(), and zoom_area.
Referenced by create_zoom().
static void create_menu_btn (GtkWidget * wgt_menubar, GtkWidget ** wgt_menubtn, GtkWidget ** wgt_menu, char * label, int side, void(*)(GtkMenuItem *, gpointer) pcb_activate) static
Definition at line 807 of file zoom.c.
Referenced by create_zoom().
GtkWidget* create_menu_item (GtkWidget * wgt_menu, char * label, char * xpm[], int sensitive, int acc_key, int acc_control, GCallback cb, gpointer user_data)
Definition at line 836 of file zoom.c.
Referenced by create_zoom().
void create_zoom (void)
Definition at line 867 of file zoom.c.
References close_app(), config, create_color(), create_menu_btn(), create_menu_item(), CONFIG::life_height, CONFIG::life_width, LifeCenterGeneration, LifeNextGen, LifeNextGens, LifePrevGen, LifeRestoreStartingGen, menu_OptionsGrid, on_FileExit_activate(), on_FileLoad_activate(), on_FileNextGens_activate(), on_FilePrevGen_activate(), on_FilePrint_activate(), on_FileSave_activate(), on_FileSaveText_activate(), on_HelpAbout_activate(), on_HelpRules_activate(), on_LifeCenterGeneration_activate(), on_LifeCenterZoom_activate(), on_LifeClear_activate(), on_LifeGraph_activate(), on_LifeInterGen_7_172_activate(), on_LifeNextGen_activate(), on_LifeRandomGen_activate(), on_LifeRestoreStartingGen_activate(), on_LifeSeekInterGen_activate(), on_LifeStats_activate(), on_OptionsGrid_activate(), on_OptionsSettings_activate(), on_RuleDefine_activate(), on_RuleLoad_activate(), on_RuleSave_activate(), on_RulesStd_activate(), on_zoom_area_button_press_event(), on_zoom_area_configure_event(), on_zoom_area_expose_event(), on_zoom_area_motion_notify_event(), on_zoom_scrolledwindow_event(), zoom_area, ZOOM_CELL_HEIGHT, ZOOM_CELL_WIDTH, zoom_maxgen, zoom_none_color, zoom_off_color, zoom_on_color, and zoom_xy.
Referenced by main().
void center_zoom (void)
Definition at line 1349 of file zoom.c.
References config, field_scrolledwnd, fielddraw, get_zoom_infos(), CONFIG::life_height, CONFIG::life_width, and zoom_area.
Referenced by clear_life(), main(), and on_LifeCenterZoom_activate().
int is_grid (void)
Definition at line 1396 of file zoom.c.
References menu_OptionsGrid.
Referenced by redraw_pixmap_zoom().
void enable_LifeCenterGeneration (const int flag)
Definition at line 1404 of file zoom.c.
References LifeCenterGeneration.
void enable_PrevGen (const int flag)
Definition at line 1410 of file zoom.c.
References LifePrevGen.
void enable_NextGen (const int flag)
Definition at line 1416 of file zoom.c.
References LifeNextGen.
void enable_NextGens (const int flag)
Definition at line 1422 of file zoom.c.
References LifeNextGens.
void enable_RestoreStartingGen (const int flag)
Definition at line 1428 of file zoom.c.
References LifeRestoreStartingGen.
Variable Documentation
GtkWidget* LifeCenterGeneration static
Definition at line 21 of file zoom.c.
Referenced by create_zoom(), and enable_LifeCenterGeneration().
GtkWidget* LifePrevGen static
Definition at line 22 of file zoom.c.
Referenced by create_zoom(), and enable_PrevGen().
GtkWidget* LifeNextGen static
Definition at line 23 of file zoom.c.
Referenced by create_zoom(), and enable_NextGen().
GtkWidget* LifeNextGens static
Definition at line 24 of file zoom.c.
Referenced by create_zoom(), and enable_NextGens().
GtkWidget* LifeRestoreStartingGen static
Definition at line 25 of file zoom.c.
Referenced by create_zoom(), and enable_RestoreStartingGen().